"""Problem staging and export routes"""

import json
import httpx
from datetime import datetime
from fastapi import APIRouter, HTTPException

from models import ConfirmProblemRequest, ExportRequest
from config import EXPORTS_DIR, staged_problems, locus_config
from latex_formatter import normalize_latex

router = APIRouter()


@router.post("/confirm-problem")
async def confirm_problem(request: ConfirmProblemRequest):
    """Stage an approved problem with automatic LaTeX normalization"""
    if request.approved:
        # Automatically normalize LaTeX to ensure proper $ delimiters
        # This handles inconsistent AI-generated scripts
        problem = request.problem.copy()
        if 'question_latex' in problem:
            problem['question_latex'] = normalize_latex(problem['question_latex'])

        staged_problems.append(problem)
        return {
            "message": "Problem staged (LaTeX normalized)",
            "staged_count": len(staged_problems)
        }
    return {
        "message": "Problem rejected",
        "staged_count": len(staged_problems)
    }


@router.get("/staged")
async def get_staged():
    """Get all staged problems"""
    return {
        "problems": staged_problems,
        "count": len(staged_problems)
    }


@router.delete("/staged")
async def clear_staged():
    """Clear staging area"""
    count = len(staged_problems)
    staged_problems.clear()
    return {
        "message": f"Cleared {count} problems",
        "staged_count": 0
    }


@router.post("/export")
async def export_problems(request: ExportRequest):
    """Export staged problems to SQL/JSON file on server"""
    if not staged_problems:
        raise HTTPException(status_code=400, detail="No problems staged")

    filename = f"problems_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}"

    if request.format == "sql":
        sql_lines = [
            "-- Generated by Locus Factory",
            f"-- Generated at: {datetime.utcnow().isoformat()}",
            f"-- Problem count: {len(staged_problems)}",
            "",
            "INSERT INTO problems (question_latex, answer_key, difficulty, main_topic, subtopic, grading_mode, answer_type, calculator_allowed, solution_latex, question_image, time_limit_seconds) VALUES"
        ]

        values = []
        for p in staged_problems:
            q = p['question_latex'].replace("'", "''")
            a = p['answer_key'].replace("'", "''")
            mt = p['main_topic'].replace("'", "''")
            st = p['subtopic'].replace("'", "''")
            gm = p['grading_mode'].replace("'", "''")
            at = p.get('answer_type', 'expression').replace("'", "''")
            ca = p.get('calculator_allowed', 'none').replace("'", "''")
            sl = p.get('solution_latex', '').replace("'", "''")
            qi = p.get('question_image', '').replace("'", "''")
            tl = p.get('time_limit_seconds')
            d = p['difficulty']
            tl_sql = 'NULL' if tl is None else str(int(tl))
            values.append(f"('{q}', '{a}', {d}, '{mt}', '{st}', '{gm}', '{at}', '{ca}', '{sl}', '{qi}', {tl_sql})")

        sql_lines.append(",\n".join(values) + ";")
        content = "\n".join(sql_lines)

        filepath = EXPORTS_DIR / f"{filename}.sql"
        filepath.write_text(content)

        return {
            "format": "sql",
            "filename": filepath.name,
            "path": str(filepath),
            "count": len(staged_problems),
            "message": f"Exported to {filepath.name}"
        }

    elif request.format == "json":
        content = json.dumps(staged_problems, indent=2)
        filepath = EXPORTS_DIR / f"{filename}.json"
        filepath.write_text(content)

        return {
            "format": "json",
            "filename": filepath.name,
            "path": str(filepath),
            "count": len(staged_problems),
            "message": f"Exported to {filepath.name}"
        }

    raise HTTPException(status_code=400, detail="Invalid format")


@router.get("/exports")
async def list_exports():
    """List all exported files"""
    exports = []
    for export_file in EXPORTS_DIR.glob("*"):
        exports.append({
            "filename": export_file.name,
            "format": export_file.suffix[1:],  # Remove dot
            "size": export_file.stat().st_size,
            "created": datetime.fromtimestamp(export_file.stat().st_mtime).isoformat(),
        })

    return {
        "exports": sorted(exports, key=lambda x: x["created"], reverse=True),
        "count": len(exports)
    }


@router.get("/exports/{filename}")
async def download_export(filename: str):
    """Download an exported file"""
    filepath = EXPORTS_DIR / filename
    if not filepath.exists():
        raise HTTPException(status_code=404, detail="File not found")

    content = filepath.read_text()
    return {
        "filename": filename,
        "content": content,
        "size": filepath.stat().st_size
    }


@router.post("/upload-to-backend/{filename}")
async def upload_to_backend(filename: str):
    """Upload an exported SQL file to Locus backend by executing it"""
    if not locus_config["backend_url"] or not locus_config["api_key"]:
        raise HTTPException(status_code=400, detail="Locus backend not configured")

    filepath = EXPORTS_DIR / filename
    if not filepath.exists():
        raise HTTPException(status_code=404, detail="Export file not found")

    # For SQL files, we need to parse and submit each problem individually
    # (The Locus backend doesn't have a SQL import endpoint)
    if filename.endswith('.json'):
        # Load JSON and submit each problem
        problems = json.loads(filepath.read_text())
    else:
        raise HTTPException(status_code=400, detail="Only JSON uploads supported for now. Use staged submit instead.")

    submitted = 0
    errors = []

    async with httpx.AsyncClient(timeout=30.0) as client:
        for i, problem in enumerate(problems):
            try:
                response = await client.post(
                    f"{locus_config['backend_url']}/api/internal/problems",
                    headers={
                        "X-API-Key": locus_config["api_key"],
                        "Content-Type": "application/json",
                    },
                    json=problem,
                )
                response.raise_for_status()
                submitted += 1
            except Exception as e:
                errors.append(f"Problem {i+1}: {str(e)[:100]}")

    return {
        "submitted": submitted,
        "total": len(problems),
        "errors": errors[:10] if errors else None,
        "message": f"Uploaded {submitted}/{len(problems)} problems to Locus"
    }
