apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-secrets
  labels:
    app: {{ .Release.Name }}-minio
type: Opaque
stringData:
  root-user: {{ .Values.minio.rootUser | required "minio.rootUser is required" | quote }}
  root-password: {{ .Values.minio.rootPassword | required "minio.rootPassword is required" | quote }}
  cloudflared-token: {{ .Values.minioTunnel.token | required "minioTunnel.token is required" | quote }}
