apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-community-secrets
type: Opaque
stringData:
  database-url: {{ required "secrets.databaseUrl is required" .Values.secrets.databaseUrl | quote }}
  jwt-secret: {{ required "secrets.jwtSecret is required" .Values.secrets.jwtSecret | quote }}
  cloudflared-token: {{ required "secrets.cloudflaredToken is required" .Values.secrets.cloudflaredToken | quote }}
